spring:
  application:
    name: money-mate-agent
  ai:
    mcp:
      server:
        protocol: STREAMABLE
        name: money-mate-agent
        version: 1.0.0
        type: SYNC
        streamable-http:
          mcp-endpoint: /mcp
        annotation-scanner:
          enabled: true

server:
  port: 9090

